name: Daily_Task

on:
  schedule:
    - cron: "0 20 * * *"  # 每天 UTC 时间 20:00 执行（北京时间 04:00）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt install -y curl wget vim git nano  
          python -m pip install --upgrade pip
          pip install jq
      - name: Fetch JSON data
        run: |
          wget -O cf_ip https://api.vvhan.com/tool/cf_ip
          wget -O addressesapi.txt https://ipdb.api.030101.xyz/?type=bestcf&country=true
      - name: Process JSON data
        run: |
          # 使用 jq 处理 JSON 数据
          jq -r '.data.v4.CM[] | "\(.ip)#\(.name)"' cf_ip >> addressesapi.txt
          jq -r '.data.v4.CU[] | "\(.ip)#\(.name)"' cf_ip >> addressesapi.txt
          jq -r '.data.v4.CT[] | "\(.ip)#\(.name)"' cf_ip >> addressesapi.txt
      - name: process file  
        run: |
          # 定义端口列表
          ports=(80,443,2052,2053,2082,2083,2086,2087,2095,2096,8080,8443,8880)
          # 读取 IP 地址和名称
          while IFS='#' read -r ip name; do
              for port in "${ports[@]}"; do
                  echo "$ip:$port#$name"
              done
          done < addressesapi.txt > addressesapi_new.txt
          
          # 将新内容覆盖到原文件
          mv addressesapi_new.txt addressesapi.txt
      - name: Show processed file content
        run: cat addressesapi.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add addressesapi.txt
          git commit -m "Update addressesapi.txt"
          git push
